# Generated by Django 3.2 on 2024-12-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='grain_type',
            field=models.CharField(default='wheat', max_length=100),
        ),
    ]
